### ISSUE TITLE
Sign in: lack of padding x (see image)

### ISSUE THREAD

**Issue by millie-wy** [millie-wy/letsCook#38]
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/89253350/164981648-3285cf39-4931-4cb9-bf81-4ff927f1a716.png">

**Comment by Willen17** [comment]
I think it already has padding. On my screen it looks good, but if i have the console located at the bottom and shrink the height of the window, the page looks like your screenshot. However, I don't think there is any devices with such a screen ratio, normally if the height is that low, the width of the screen is also lower. And with a normal screen width to height ratio I don't think this problem will occur?
